name: Coding Standards

on:
  pull_request:
  push:
    branches:
      - 'feature/**'
      - 'fix/**'

env:
  DEFAULT_NODE_VERSION: 14

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        # https://github.com/marketplace/actions/setup-node-js-environment
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}

      - name: Cache node_modules
        uses: actions/cache@v2
        id: cache-nodemodules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.DEFAULT_NODE_VERSION }}-nodemodules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: ${{ steps.cache-nodemodules.outputs.cache-hit != 'true' }}
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

